kind: pipeline
type: docker
name: default

trigger:
  branch:
    - tr-27-containerization

clone:
  disable: true

steps:
  - name: clone
    image: drone/git
    commands:
      - git clone http://192.168.1.101:3000/kcbimonte/Treasury-MK3_Angular.git .

  - name: build
    image: node:14-alpine
    commands:
      - npm install
      - npm run ng build


